### Crash Data-QueensLand Australia(Data Quality Check)

##### Let us start by importing relevant libraries

In [1]:
#Importing Libraries and loading data sets
import pandas as pd
import numpy as np
import datetime as dt
import warnings
warnings.filterwarnings('ignore')
crash_locations = pd.read_csv('crash_data_queensland_1_crash_locations.csv')
road_casualties = pd.read_csv('crash_data_queensland_a_road_casualties.csv')
driver_involvement = pd.read_csv('crash_data_queensland_b_driver_involvement.csv')
use_helment = pd.read_csv('crash_data_queensland_c_restraint_helmet_use.csv')
vehicle_involvement = pd.read_csv('crash_data_queensland_d_vehicle_involvement.csv')
specific_factors = pd.read_csv('crash_data_queensland_e_alcohol_speed_fatigue_defect.csv')

we would be looking at the data individually to check the integrity, quality and completness of the data

Our Data Cleaning steps:
Data cleaning is a crucial step in the data analysis process that involves identifying and correcting errors, inconsistencies, and missing values in a dataset. Here are some general steps we will follow when performing the data cleaning:

1.Identify the data quality issues: We start by exploring the data to identify any data quality issues, such as missing values, duplicates, incorrect data types, or inconsistent formatting.

2.Remove duplicates: If we find duplicate records in the dataset, we remove them to avoid overrepresentation of certain data points.

3.Handle missing values: We will Decide how to handle missing values, whether by imputing them with a reasonable estimate, deleting the entire record or column, or keeping them as missing values.

4.Standardize data format: We will Standardize the format of your data to ensure consistency, for example, by converting data to a common data type or unit of measurement.

5.Document data cleaning steps: Keep track of the steps we have taken during data cleaning, so that others can understand how we have processed the data and reproduce our results.

By following these general steps(not in particular order), we can perform effective data cleaning that will help us get better insights from your data

### 1.Getting an Understanding of the data

#### Having a look at available data

In [2]:
#let's look at all the columns
pd.set_option('display.max_columns',None)
crash_locations.head()

,Crash_Ref_Number,Crash_Severity,Crash_Year,Crash_Month,Crash_Day_Of_Week,Crash_Hour,Crash_Nature,Crash_Type,Crash_Longitude,Crash_Latitude,Crash_Street,Crash_Street_Intersecting,State_Road_Name,Loc_Suburb,Loc_Local_Government_Area,Loc_Post_Code,Loc_Police_Division,Loc_Police_District,Loc_Police_Region,Loc_Queensland_Transport_Region,Loc_Main_Roads_Region,Loc_ABS_Statistical_Area_2,Loc_ABS_Statistical_Area_3,Loc_ABS_Statistical_Area_4,Loc_ABS_Remoteness,Loc_State_Electorate,Loc_Federal_Electorate,Crash_Controlling_Authority,Crash_Roadway_Feature,Crash_Traffic_Control,Crash_Speed_Limit,Crash_Road_Surface_Condition,Crash_Atmospheric_Condition,Crash_Lighting_Condition,Crash_Road_Horiz_Align,Crash_Road_Vert_Align,Crash_DCA_Code,Crash_DCA_Description,Crash_DCA_Group_Description,DCA_Key_Approach_Dir,Count_Casualty_Fatality,Count_Casualty_Hospitalised,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_Total,Count_Unit_Car,Count_Unit_Motorcycle_Moped,Count_Unit_Truck,Count_Unit_Bus,Count_Unit_Bicycle,Count_Unit_Pedestrian,Count_Unit_Other
0,1,Hospitalisation,2001,January,Monday,6,Head-on,Multi-Vehicle,153.052207,-27.586358,Gretel St,NaN,NaN,Sunnybank Hills,Brisbane City,4109,Acacia Ridge,South Brisbane,Brisbane,SEQ South,Metropolitan,Sunnybank Hills,Sunnybank,Brisbane - South,Major Cities,Stretton,Moreton,Locally-controlled,No Roadway Feature,No traffic control,0 - 50 km/h,Sealed - Dry,Clear,Daylight,Curved - view obscured,Grade,201.0,Veh'S Opposite Approach: Head On,Head-on,S,0,1,0,0,1,1,0,0,0,1,0,0
1,2,Property damage only,2001,January,Wednesday,9,Angle,Multi-Vehicle,153.064920,-27.595907,Gowan Rd,NaN,NaN,Sunnybank Hills,Brisbane City,4109,Acacia Ridge,South Brisbane,Brisbane,SEQ South,Metropolitan,Runcorn,Sunnybank,Brisbane - South,Major Cities,Stretton,Moreton,Locally-controlled,No Roadway Feature,No traffic control,60 km/h,Sealed - Dry,Clear,Daylight,Straight,Crest,406.0,Veh'S Manoeuvring: Leaving Driveway,Vehicle leaving driveway,S,0,0,0,0,0,2,0,0,0,0,0,0
2,3,Minor injury,2001,January,Thursday,8,Rear-end,Multi-Vehicle,153.058444,-27.599409,Hellawell Rd,Pinelands Rd,NaN,Sunnybank Hills,Brisbane City,4109,Acacia Ridge,South Brisbane,Brisbane,SEQ South,Metropolitan,Sunnybank Hills,Sunnybank,Brisbane - South,Major Cities,Stretton,Moreton,Locally-controlled,Intersection - Cross,Operating traffic lights,60 km/h,Sealed - Dry,Clear,Daylight,Straight,Grade,301.0,Veh'S Same Direction: Rear End,Rear-end,E,0,0,0,1,1,2,0,0,0,0,0,0
3,4,Property damage only,2001,January,Sunday,8,Hit object,Single Vehicle,153.081083,-27.598882,Beenleigh Rd,Persse Rd,NaN,Runcorn,Brisbane City,4113,Upper Mount Gravatt,South Brisbane,Brisbane,SEQ South,Metropolitan,Runcorn,Sunnybank,Brisbane - South,Major Cities,Stretton,Moreton,Locally-controlled,Intersection - T-Junction,Operating traffic lights,60 km/h,Sealed - Dry,Clear,Daylight,Straight,Level,703.0,Off Path-Straight: Left Off Cway Hit Obj,Off carriageway on straight hit object,N,0,0,0,0,0,1,0,0,0,0,0,0
4,5,Property damage only,2001,January,Tuesday,16,Overturned,Single Vehicle,0.000009,-0.000010,Anderson St,NaN,NaN,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Locally-controlled,No Roadway Feature,No traffic control,60 km/h,Unsealed - Dry,Clear,Daylight,Straight,Level,702.0,Off Path-Straight: Right Off Cway,Off carriageway on straight,E,0,0,0,0,0,1,0,0,0,0,0,0

In [3]:
#Overview of data
crash_locations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367230 entries, 0 to 367229
Data columns (total 52 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Crash_Ref_Number                 367230 non-null  int64
 1   Crash_Severity                   367230 non-null  object
 2   Crash_Year                       367230 non-null  int64
 3   Crash_Month                      367230 non-null  object
 4   Crash_Day_Of_Week                367230 non-null  object
 5   Crash_Hour                       367230 non-null  int64
 6   Crash_Nature                     367230 non-null  object
 7   Crash_Type                       367230 non-null  object
 8   Crash_Longitude                  367230 non-null  float64
 9   Crash_Latitude                   367230 non-null  float64
 10  Crash_Street                     367215 non-null  object
 11  Crash_Street_Intersecting        159264 non-null  object
 12  State_Road_Name                  169672 non-null  object
 13  Loc_Suburb                       367230 non-null  object
 14  Loc_Local_Government_Area        367230 non-null  object
 15  Loc_Post_Code                    367230 non-null  object
 16  Loc_Police_Division              367230 non-null  object
 17  Loc_Police_District              367230 non-null  object
 18  Loc_Police_Region                367230 non-null  object
 19  Loc_Queensland_Transport_Region  367230 non-null  object
 20  Loc_Main_Roads_Region            367230 non-null  object
 21  Loc_ABS_Statistical_Area_2       367230 non-null  object
 22  Loc_ABS_Statistical_Area_3       367230 non-null  object
 23  Loc_ABS_Statistical_Area_4       367230 non-null  object
 24  Loc_ABS_Remoteness               367230 non-null  object
 25  Loc_State_Electorate             367230 non-null  object
 26  Loc_Federal_Electorate           367230 non-null  object
 27  Crash_Controlling_Authority      367230 non-null  object
 28  Crash_Roadway_Feature            367230 non-null  object
 29  Crash_Traffic_Control            367230 non-null  object
 30  Crash_Speed_Limit                367227 non-null  object
 31  Crash_Road_Surface_Condition     367230 non-null  object
 32  Crash_Atmospheric_Condition      367230 non-null  object
 33  Crash_Lighting_Condition         367230 non-null  object
 34  Crash_Road_Horiz_Align           367230 non-null  object
 35  Crash_Road_Vert_Align            367229 non-null  object
 36  Crash_DCA_Code                   367146 non-null  float64
 37  Crash_DCA_Description            367146 non-null  object
 38  Crash_DCA_Group_Description      367230 non-null  object
 39  DCA_Key_Approach_Dir             361749 non-null  object
 40  Count_Casualty_Fatality          367230 non-null  int64
 41  Count_Casualty_Hospitalised      367230 non-null  int64
 42  Count_Casualty_MedicallyTreated  367230 non-null  int64
 43  Count_Casualty_MinorInjury       367230 non-null  int64
 44  Count_Casualty_Total             367230 non-null  int64
 45  Count_Unit_Car                   367230 non-null  int64
 46  Count_Unit_Motorcycle_Moped      367230 non-null  int64
 47  Count_Unit_Truck                 367230 non-null  int64
 48  Count_Unit_Bus                   367230 non-null  int64
 49  Count_Unit_Bicycle               367230 non-null  int64
 50  Count_Unit_Pedestrian            367230 non-null  int64
 51  Count_Unit_Other                 367230 non-null  int64
dtypes: float64(3), int64(15), object(34)
memory usage: 145.7+ MB

In [4]:
road_casualties.head()

,Crash_Year,Crash_Police_Region,Casualty_Severity,Casualty_AgeGroup,Casualty_Gender,Casualty_RoadUserType,Casualty_Count
0,2006,North Coast,Medically treated,40 to 49,Female,Driver,71
1,2006,South Eastern,Medically treated,40 to 49,Male,Driver,54
2,2006,Southern,Medically treated,0 to 16,Female,Pedestrian,7
3,2007,North Coast,Medically treated,40 to 49,Male,Passenger,6
4,2007,Southern,Medically treated,17 to 24,Female,Driver,79

In [5]:
road_casualties.info()
#there are no null value in this table and the datatypes are correct

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32527 entries, 0 to 32526
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Crash_Year             32527 non-null  int64
 1   Crash_Police_Region    32527 non-null  object
 2   Casualty_Severity      32527 non-null  object
 3   Casualty_AgeGroup      32527 non-null  object
 4   Casualty_Gender        32527 non-null  object
 5   Casualty_RoadUserType  32527 non-null  object
 6   Casualty_Count         32527 non-null  int64
dtypes: int64(2), object(5)
memory usage: 1.7+ MB

In [6]:
driver_involvement.head()

,Crash_Year,Crash_Police_Region,Crash_Severity,Involving_Male_Driver,Involving_Female_Driver,Involving_Young_Driver_16-24,Involving_Senior_Driver_60plus,Involving_Provisional_Driver,Involving_Overseas_Licensed_Driver,Involving_Unlicensed_Driver,Count_Crashes,Count_Casualty_Fatality,Count_Casualty_Hospitalised,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_All
0,2001,Brisbane,Fatal,No,No,No,No,No,No,No,1,1,0,0,0,1
1,2001,Brisbane,Fatal,No,Yes,No,No,No,No,No,4,4,1,0,0,5
2,2001,Brisbane,Fatal,No,Yes,No,Yes,No,No,No,2,2,0,0,0,2
3,2001,Brisbane,Fatal,No,Yes,No,Yes,No,No,Yes,1,1,0,0,0,1
4,2001,Brisbane,Fatal,No,Yes,No,Yes,Yes,No,No,1,1,1,0,0,2

In [7]:
driver_involvement.info()
#the data is complete with correct datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19896 entries, 0 to 19895
Data columns (total 16 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Crash_Year                          19896 non-null  int64
 1   Crash_Police_Region                 19896 non-null  object
 2   Crash_Severity                      19896 non-null  object
 3   Involving_Male_Driver               19896 non-null  object
 4   Involving_Female_Driver             19896 non-null  object
 5   Involving_Young_Driver_16-24        19896 non-null  object
 6   Involving_Senior_Driver_60plus      19896 non-null  object
 7   Involving_Provisional_Driver        19896 non-null  object
 8   Involving_Overseas_Licensed_Driver  19896 non-null  object
 9   Involving_Unlicensed_Driver         19896 non-null  object
 10  Count_Crashes                       19896 non-null  int64
 11  Count_Casualty_Fatality             19896 non-null  int64
 12  Count_Casualty_Hospitalised         19896 non-null  int64
 13  Count_Casualty_MedicallyTreated     19896 non-null  int64
 14  Count_Casualty_MinorInjury          19896 non-null  int64
 15  Count_Casualty_All                  19896 non-null  int64
dtypes: int64(7), object(9)
memory usage: 2.4+ MB

In [8]:
use_helment.head()

,Crash_Year,Crash_PoliceRegion,Casualty_Severity,Casualty_AgeGroup,Casualty_Gender,Casualty_Road_User_Type,Casualty_Restraint_Helmet_Use,Casualty_Count
0,2001,Brisbane,Fatality,0 to 16,Female,Vehicle Occupant,Restrained,1
1,2001,Brisbane,Fatality,17 to 24,Female,Vehicle Occupant,Restrained,1
2,2001,Brisbane,Fatality,25 to 29,Female,Vehicle Occupant,Restraint Use Not determined,1
3,2001,Brisbane,Fatality,30 to 39,Female,Vehicle Occupant,Restraint Use Not determined,1
4,2001,Brisbane,Fatality,30 to 39,Female,Vehicle Occupant,Unrestrained,1

In [9]:
use_helment.info()
#No null values in this dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36212 entries, 0 to 36211
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Crash_Year                     36212 non-null  int64
 1   Crash_PoliceRegion             36212 non-null  object
 2   Casualty_Severity              36212 non-null  object
 3   Casualty_AgeGroup              36212 non-null  object
 4   Casualty_Gender                36212 non-null  object
 5   Casualty_Road_User_Type        36212 non-null  object
 6   Casualty_Restraint_Helmet_Use  36212 non-null  object
 7   Casualty_Count                 36212 non-null  int64
dtypes: int64(2), object(6)
memory usage: 2.2+ MB

In [10]:
vehicle_involvement.head()

,Crash_Year,Crash_Police_Region,Crash_Severity,Involving_Motorcycle_Moped,Involving_Truck,Involving_Bus,Count_Crashes,Count_Casualty_Fatality,Count_Casualty_Hospitalised,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_All
0,2001,Brisbane,Fatal,No,No,No,36,38,18,1,0,57
1,2001,Brisbane,Fatal,No,No,Yes,1,1,1,0,0,2
2,2001,Brisbane,Fatal,No,Yes,No,1,1,0,1,2,4
3,2001,Brisbane,Fatal,Yes,No,No,5,5,0,2,0,7
4,2001,Brisbane,Fatal,Yes,Yes,No,1,1,0,0,0,1

In [11]:
vehicle_involvement.info()
#the dataset does not have missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3246 entries, 0 to 3245
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Crash_Year                       3246 non-null   int64
 1   Crash_Police_Region              3246 non-null   object
 2   Crash_Severity                   3246 non-null   object
 3   Involving_Motorcycle_Moped       3246 non-null   object
 4   Involving_Truck                  3246 non-null   object
 5   Involving_Bus                    3246 non-null   object
 6   Count_Crashes                    3246 non-null   int64
 7   Count_Casualty_Fatality          3246 non-null   int64
 8   Count_Casualty_Hospitalised      3246 non-null   int64
 9   Count_Casualty_MedicallyTreated  3246 non-null   int64
 10  Count_Casualty_MinorInjury       3246 non-null   int64
 11  Count_Casualty_All               3246 non-null   int64
dtypes: int64(7), object(5)
memory usage: 304.4+ KB

In [12]:
specific_factors.head()

,Crash_Year,Crash_Police_Region,Crash_Severity,Involving_Drink_Driving,Involving_Driver_Speed,Involving_Fatigued_Driver,Involving_Defective_Vehicle,Count_Crashes,Count_Fatality,Count_Hospitalised,Count_Medically_Treated,Count_Minor_Injury,Count_All_Casualties
0,2001,Brisbane,Fatal,No,No,No,No,25,25,6,4,2,37
1,2001,Brisbane,Fatal,No,No,No,Yes,1,1,0,0,0,1
2,2001,Brisbane,Fatal,No,Yes,No,No,8,8,5,0,0,13
3,2001,Brisbane,Fatal,Yes,No,No,No,2,2,0,0,0,2
4,2001,Brisbane,Fatal,Yes,No,No,Yes,1,1,3,0,0,4

In [13]:
specific_factors.info()
#There are no mising values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4799 entries, 0 to 4798
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Crash_Year                   4799 non-null   int64
 1   Crash_Police_Region          4799 non-null   object
 2   Crash_Severity               4799 non-null   object
 3   Involving_Drink_Driving      4799 non-null   object
 4   Involving_Driver_Speed       4799 non-null   object
 5   Involving_Fatigued_Driver    4799 non-null   object
 6   Involving_Defective_Vehicle  4799 non-null   object
 7   Count_Crashes                4799 non-null   int64
 8   Count_Fatality               4799 non-null   int64
 9   Count_Hospitalised           4799 non-null   int64
 10  Count_Medically_Treated      4799 non-null   int64
 11  Count_Minor_Injury           4799 non-null   int64
 12  Count_All_Casualties         4799 non-null   int64
dtypes: int64(7), object(6)
memory usage: 487.5+ KB

The crash_locations dataset is the only dataset with missing values. Going forward, we will be looking at filling some of the missing values and dropping some of the irrelevant columns

### 2.1 Dealing with inconsistent formatting and Standardising our Datatype

In [14]:
crash_locations.head()

,Crash_Ref_Number,Crash_Severity,Crash_Year,Crash_Month,Crash_Day_Of_Week,Crash_Hour,Crash_Nature,Crash_Type,Crash_Longitude,Crash_Latitude,Crash_Street,Crash_Street_Intersecting,State_Road_Name,Loc_Suburb,Loc_Local_Government_Area,Loc_Post_Code,Loc_Police_Division,Loc_Police_District,Loc_Police_Region,Loc_Queensland_Transport_Region,Loc_Main_Roads_Region,Loc_ABS_Statistical_Area_2,Loc_ABS_Statistical_Area_3,Loc_ABS_Statistical_Area_4,Loc_ABS_Remoteness,Loc_State_Electorate,Loc_Federal_Electorate,Crash_Controlling_Authority,Crash_Roadway_Feature,Crash_Traffic_Control,Crash_Speed_Limit,Crash_Road_Surface_Condition,Crash_Atmospheric_Condition,Crash_Lighting_Condition,Crash_Road_Horiz_Align,Crash_Road_Vert_Align,Crash_DCA_Code,Crash_DCA_Description,Crash_DCA_Group_Description,DCA_Key_Approach_Dir,Count_Casualty_Fatality,Count_Casualty_Hospitalised,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_Total,Count_Unit_Car,Count_Unit_Motorcycle_Moped,Count_Unit_Truck,Count_Unit_Bus,Count_Unit_Bicycle,Count_Unit_Pedestrian,Count_Unit_Other
0,1,Hospitalisation,2001,January,Monday,6,Head-on,Multi-Vehicle,153.052207,-27.586358,Gretel St,NaN,NaN,Sunnybank Hills,Brisbane City,4109,Acacia Ridge,South Brisbane,Brisbane,SEQ South,Metropolitan,Sunnybank Hills,Sunnybank,Brisbane - South,Major Cities,Stretton,Moreton,Locally-controlled,No Roadway Feature,No traffic control,0 - 50 km/h,Sealed - Dry,Clear,Daylight,Curved - view obscured,Grade,201.0,Veh'S Opposite Approach: Head On,Head-on,S,0,1,0,0,1,1,0,0,0,1,0,0
1,2,Property damage only,2001,January,Wednesday,9,Angle,Multi-Vehicle,153.064920,-27.595907,Gowan Rd,NaN,NaN,Sunnybank Hills,Brisbane City,4109,Acacia Ridge,South Brisbane,Brisbane,SEQ South,Metropolitan,Runcorn,Sunnybank,Brisbane - South,Major Cities,Stretton,Moreton,Locally-controlled,No Roadway Feature,No traffic control,60 km/h,Sealed - Dry,Clear,Daylight,Straight,Crest,406.0,Veh'S Manoeuvring: Leaving Driveway,Vehicle leaving driveway,S,0,0,0,0,0,2,0,0,0,0,0,0
2,3,Minor injury,2001,January,Thursday,8,Rear-end,Multi-Vehicle,153.058444,-27.599409,Hellawell Rd,Pinelands Rd,NaN,Sunnybank Hills,Brisbane City,4109,Acacia Ridge,South Brisbane,Brisbane,SEQ South,Metropolitan,Sunnybank Hills,Sunnybank,Brisbane - South,Major Cities,Stretton,Moreton,Locally-controlled,Intersection - Cross,Operating traffic lights,60 km/h,Sealed - Dry,Clear,Daylight,Straight,Grade,301.0,Veh'S Same Direction: Rear End,Rear-end,E,0,0,0,1,1,2,0,0,0,0,0,0
3,4,Property damage only,2001,January,Sunday,8,Hit object,Single Vehicle,153.081083,-27.598882,Beenleigh Rd,Persse Rd,NaN,Runcorn,Brisbane City,4113,Upper Mount Gravatt,South Brisbane,Brisbane,SEQ South,Metropolitan,Runcorn,Sunnybank,Brisbane - South,Major Cities,Stretton,Moreton,Locally-controlled,Intersection - T-Junction,Operating traffic lights,60 km/h,Sealed - Dry,Clear,Daylight,Straight,Level,703.0,Off Path-Straight: Left Off Cway Hit Obj,Off carriageway on straight hit object,N,0,0,0,0,0,1,0,0,0,0,0,0
4,5,Property damage only,2001,January,Tuesday,16,Overturned,Single Vehicle,0.000009,-0.000010,Anderson St,NaN,NaN,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Locally-controlled,No Roadway Feature,No traffic control,60 km/h,Unsealed - Dry,Clear,Daylight,Straight,Level,702.0,Off Path-Straight: Right Off Cway,Off carriageway on straight,E,0,0,0,0,0,1,0,0,0,0,0,0

In [15]:
#making a copy of the data
crash_loc = crash_locations.copy()

In [16]:
crash_loc['Crash_Nature'].value_counts()

Angle                            109955
Rear-end                          90408
Hit object                        79770
Overturned                        18653
Sideswipe                         17322
Hit pedestrian                    14545
Hit parked vehicle                12492
Fall from vehicle                 10038
Head-on                            8860
Hit animal                         3534
Non-collision - miscellaneous       771
Struck by external load             468
Collision - miscellaneous           338
Other                                57
Struck by internal load              19
Name: Crash_Nature, dtype: int64

In [17]:
crash_loc['Crash_Type'].value_counts()

Multi-Vehicle     226545
Single Vehicle    120953
Hit pedestrian     14545
Other               5187
Name: Crash_Type, dtype: int64

In [18]:
crash_loc['Loc_Police_Region'].value_counts()

Brisbane         109835
North Coast       69779
South Eastern     64541
Southern          46122
Central           33274
Far Northern      22344
Northern          20737
Unknown             598
Name: Loc_Police_Region, dtype: int64

In [19]:
crash_loc['Crash_DCA_Group_Description'].value_counts()

Rear-end                                    88150
Intersection from adjacent approaches       53668
Off carriageway on straight hit object      36033
Opposing vehicles turning                   32780
Other                                       29112
Off carriageway on curve hit object         26519
Vehicle leaving driveway                    14149
Pedestrian                                  12868
Head-on                                     12152
Lane changes                                11709
Out of control on straight                   7988
Parallel lanes turning                       7896
Hit parked vehicle                           7892
Out of control on curve                      7716
Off carriageway on straight                  6563
Off carriageway on curve                     4197
Hit animal                                   3410
Overtaking same direction                    1956
U-turn                                       1918
Train                                         280
Hit permanent obstruction on carriageway      274
Name: Crash_DCA_Group_Description, dtype: int64

Here we show some of the counts for various of the data categories which are consistent, also all the data we would be looking at using from this dataset are also complete

In [20]:
road_cas = road_casualties.copy()

In [21]:
road_cas.head()

,Crash_Year,Crash_Police_Region,Casualty_Severity,Casualty_AgeGroup,Casualty_Gender,Casualty_RoadUserType,Casualty_Count
0,2006,North Coast,Medically treated,40 to 49,Female,Driver,71
1,2006,South Eastern,Medically treated,40 to 49,Male,Driver,54
2,2006,Southern,Medically treated,0 to 16,Female,Pedestrian,7
3,2007,North Coast,Medically treated,40 to 49,Male,Passenger,6
4,2007,Southern,Medically treated,17 to 24,Female,Driver,79

In [22]:
road_cas['Crash_Police_Region'].value_counts()

Brisbane         5368
North Coast      5295
South Eastern    5093
Southern         4436
Central          4124
Far Northern     4096
Northern         3829
Unknown           286
Name: Crash_Police_Region, dtype: int64

In [23]:
road_cas['Casualty_Severity'].value_counts()

Hospitalised         10709
Medically treated    10147
Minor injury          8228
Fatality              3443
Name: Casualty_Severity, dtype: int64

In [24]:
road_cas['Casualty_AgeGroup'].value_counts()
#later we will drop the categories with unknown in this attribute

17 to 24       4572
30 to 39       4419
40 to 49       4296
50 to 59       4040
25 to 29       3968
60 to 74       3691
0 to 16        3639
75 and over    2632
Unknown        1270
Name: Casualty_AgeGroup, dtype: int64

In [25]:
road_cas['Casualty_Gender'].value_counts()
#we would change the unknown here to Male since it is most common

Male       17948
Female     13977
Unknown      602
Name: Casualty_Gender, dtype: int64

In [26]:
road_cas['Casualty_RoadUserType'].value_counts()

Passenger       8453
Driver          8436
Motorcyclist    5377
Pedestrian      5372
Bicyclist       4587
Other            302
Name: Casualty_RoadUserType, dtype: int64

In [27]:
#replacing values
road_cas['Casualty_Gender'] = road_cas['Casualty_Gender'].str.replace('Unknown','Male')
road_cas['Casualty_Gender'].value_counts()

Male      18550
Female    13977
Name: Casualty_Gender, dtype: int64

In [28]:
#removing Unknown from the Agegroup
road_cas= road_cas[road_cas['Casualty_AgeGroup'] != 'Unknown']

In [29]:
road_cas['Casualty_AgeGroup'].value_counts()

17 to 24       4572
30 to 39       4419
40 to 49       4296
50 to 59       4040
25 to 29       3968
60 to 74       3691
0 to 16        3639
75 and over    2632
Name: Casualty_AgeGroup, dtype: int64

In [30]:
driver_involvement
#we will not be using this data in our analysis since similar information is already on the road_casualities dataset

,Crash_Year,Crash_Police_Region,Crash_Severity,Involving_Male_Driver,Involving_Female_Driver,Involving_Young_Driver_16-24,Involving_Senior_Driver_60plus,Involving_Provisional_Driver,Involving_Overseas_Licensed_Driver,Involving_Unlicensed_Driver,Count_Crashes,Count_Casualty_Fatality,Count_Casualty_Hospitalised,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_All
0,2001,Brisbane,Fatal,No,No,No,No,No,No,No,1,1,0,0,0,1
1,2001,Brisbane,Fatal,No,Yes,No,No,No,No,No,4,4,1,0,0,5
2,2001,Brisbane,Fatal,No,Yes,No,Yes,No,No,No,2,2,0,0,0,2
3,2001,Brisbane,Fatal,No,Yes,No,Yes,No,No,Yes,1,1,0,0,0,1
4,2001,Brisbane,Fatal,No,Yes,No,Yes,Yes,No,No,1,1,1,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19891,2021,Southern,Minor injury,Yes,Yes,No,Yes,No,No,Yes,1,0,0,0,1,1
19892,2021,Southern,Minor injury,Yes,Yes,Yes,No,No,No,No,10,0,0,0,16,16
19893,2021,Southern,Minor injury,Yes,Yes,Yes,No,Yes,No,No,16,0,0,0,21,21
19894,2021,Southern,Minor injury,Yes,Yes,Yes,Yes,No,No,No,4,0,0,0,8,8
19895,2021,Southern,Minor injury,Yes,Yes,Yes,Yes,Yes,No,No,1,0,0,0,1,1

In [31]:
use_helment

,Crash_Year,Crash_PoliceRegion,Casualty_Severity,Casualty_AgeGroup,Casualty_Gender,Casualty_Road_User_Type,Casualty_Restraint_Helmet_Use,Casualty_Count
0,2001,Brisbane,Fatality,0 to 16,Female,Vehicle Occupant,Restrained,1
1,2001,Brisbane,Fatality,17 to 24,Female,Vehicle Occupant,Restrained,1
2,2001,Brisbane,Fatality,25 to 29,Female,Vehicle Occupant,Restraint Use Not determined,1
3,2001,Brisbane,Fatality,30 to 39,Female,Vehicle Occupant,Restraint Use Not determined,1
4,2001,Brisbane,Fatality,30 to 39,Female,Vehicle Occupant,Unrestrained,1
...,...,...,...,...,...,...,...,...
36207,2021,Southern,Minor injury,50 to 59,Male,Vehicle Occupant,Restraint Use Not determined,1
36208,2021,Southern,Minor injury,60 to 74,Male,Motorcyclist,Helmet Worn,4
36209,2021,Southern,Minor injury,60 to 74,Male,Vehicle Occupant,Restrained,15
36210,2021,Southern,Minor injury,75 and over,Male,Bicyclist,Helmet Worn,1
36211,2021,Southern,Minor injury,75 and over,Male,Vehicle Occupant,Restrained,7

In [32]:
restraint = use_helment.copy()

In [33]:
restraint.head()

,Crash_Year,Crash_PoliceRegion,Casualty_Severity,Casualty_AgeGroup,Casualty_Gender,Casualty_Road_User_Type,Casualty_Restraint_Helmet_Use,Casualty_Count
0,2001,Brisbane,Fatality,0 to 16,Female,Vehicle Occupant,Restrained,1
1,2001,Brisbane,Fatality,17 to 24,Female,Vehicle Occupant,Restrained,1
2,2001,Brisbane,Fatality,25 to 29,Female,Vehicle Occupant,Restraint Use Not determined,1
3,2001,Brisbane,Fatality,30 to 39,Female,Vehicle Occupant,Restraint Use Not determined,1
4,2001,Brisbane,Fatality,30 to 39,Female,Vehicle Occupant,Unrestrained,1

In [34]:
restraint['Crash_PoliceRegion'].value_counts()

Brisbane         6248
North Coast      6037
South Eastern    5826
Southern         4858
Central          4485
Far Northern     4386
Northern         4081
Unknown           291
Name: Crash_PoliceRegion, dtype: int64

In [35]:
restraint['Casualty_Severity'].value_counts()

Hospitalised         12325
Medically treated    11385
Minor injury          9093
Fatality              3409
Name: Casualty_Severity, dtype: int64

In [36]:
restraint['Casualty_AgeGroup'].value_counts()

17 to 24       5593
30 to 39       5200
40 to 49       4899
25 to 29       4505
50 to 59       4328
0 to 16        4316
60 to 74       3746
75 and over    2391
Unknown        1234
Name: Casualty_AgeGroup, dtype: int64

In [37]:
#removing Unknown from the Agegroup
restraint= restraint[restraint['Casualty_AgeGroup'] != 'Unknown']

In [38]:
restraint['Casualty_Gender'].value_counts()

Male       20865
Female     13839
Unknown      274
Name: Casualty_Gender, dtype: int64

In [39]:
#replacing values
restraint['Casualty_Gender'] = restraint['Casualty_Gender'].str.replace('Unknown','Male')
restraint['Casualty_Gender'].value_counts()

Male      21139
Female    13839
Name: Casualty_Gender, dtype: int64

In [40]:
restraint['Casualty_Road_User_Type'].value_counts()

Vehicle Occupant    21558
Motorcyclist         7130
Bicyclist            6290
Name: Casualty_Road_User_Type, dtype: int64

In [41]:
restraint['Casualty_Restraint_Helmet_Use'].value_counts()

Helmet Worn                     9090
Restrained                      8443
Restraint Use Not determined    7376
Unrestrained                    4466
Helmet Use Not determined       2440
Helmet Not Worn                 1833
Not applicable                  1330
Name: Casualty_Restraint_Helmet_Use, dtype: int64

In [42]:
#looking at vehicle involvement
vehicle_invol = vehicle_involvement.copy()
vehicle_invol.head()
#we would not be using this dataset too since the crash location already has similar information

,Crash_Year,Crash_Police_Region,Crash_Severity,Involving_Motorcycle_Moped,Involving_Truck,Involving_Bus,Count_Crashes,Count_Casualty_Fatality,Count_Casualty_Hospitalised,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_All
0,2001,Brisbane,Fatal,No,No,No,36,38,18,1,0,57
1,2001,Brisbane,Fatal,No,No,Yes,1,1,1,0,0,2
2,2001,Brisbane,Fatal,No,Yes,No,1,1,0,1,2,4
3,2001,Brisbane,Fatal,Yes,No,No,5,5,0,2,0,7
4,2001,Brisbane,Fatal,Yes,Yes,No,1,1,0,0,0,1

In [43]:
#looking at the factors dataset
factors = specific_factors.copy()
factors.head()

,Crash_Year,Crash_Police_Region,Crash_Severity,Involving_Drink_Driving,Involving_Driver_Speed,Involving_Fatigued_Driver,Involving_Defective_Vehicle,Count_Crashes,Count_Fatality,Count_Hospitalised,Count_Medically_Treated,Count_Minor_Injury,Count_All_Casualties
0,2001,Brisbane,Fatal,No,No,No,No,25,25,6,4,2,37
1,2001,Brisbane,Fatal,No,No,No,Yes,1,1,0,0,0,1
2,2001,Brisbane,Fatal,No,Yes,No,No,8,8,5,0,0,13
3,2001,Brisbane,Fatal,Yes,No,No,No,2,2,0,0,0,2
4,2001,Brisbane,Fatal,Yes,No,No,Yes,1,1,3,0,0,4

In [44]:
#looking at categories
factors['Involving_Drink_Driving'].value_counts()

No     2931
Yes    1868
Name: Involving_Drink_Driving, dtype: int64

In [45]:
factors['Involving_Driver_Speed'].value_counts()

No     3077
Yes    1722
Name: Involving_Driver_Speed, dtype: int64

In [46]:
factors['Involving_Fatigued_Driver'].value_counts()

No     3702
Yes    1097
Name: Involving_Fatigued_Driver, dtype: int64

In [47]:
factors['Involving_Defective_Vehicle'].value_counts()

No     3671
Yes    1128
Name: Involving_Defective_Vehicle, dtype: int64

### 2.2 Dealing with Missing Values and dropping columns

In [48]:
crash_loc.info()
#We see that the year,month and day of the week has the a wrongly assigned datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367230 entries, 0 to 367229
Data columns (total 52 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Crash_Ref_Number                 367230 non-null  int64
 1   Crash_Severity                   367230 non-null  object
 2   Crash_Year                       367230 non-null  int64
 3   Crash_Month                      367230 non-null  object
 4   Crash_Day_Of_Week                367230 non-null  object
 5   Crash_Hour                       367230 non-null  int64
 6   Crash_Nature                     367230 non-null  object
 7   Crash_Type                       367230 non-null  object
 8   Crash_Longitude                  367230 non-null  float64
 9   Crash_Latitude                   367230 non-null  float64
 10  Crash_Street                     367215 non-null  object
 11  Crash_Street_Intersecting        159264 non-null  object
 12  State_Road_Name                  169672 non-null  object
 13  Loc_Suburb                       367230 non-null  object
 14  Loc_Local_Government_Area        367230 non-null  object
 15  Loc_Post_Code                    367230 non-null  object
 16  Loc_Police_Division              367230 non-null  object
 17  Loc_Police_District              367230 non-null  object
 18  Loc_Police_Region                367230 non-null  object
 19  Loc_Queensland_Transport_Region  367230 non-null  object
 20  Loc_Main_Roads_Region            367230 non-null  object
 21  Loc_ABS_Statistical_Area_2       367230 non-null  object
 22  Loc_ABS_Statistical_Area_3       367230 non-null  object
 23  Loc_ABS_Statistical_Area_4       367230 non-null  object
 24  Loc_ABS_Remoteness               367230 non-null  object
 25  Loc_State_Electorate             367230 non-null  object
 26  Loc_Federal_Electorate           367230 non-null  object
 27  Crash_Controlling_Authority      367230 non-null  object
 28  Crash_Roadway_Feature            367230 non-null  object
 29  Crash_Traffic_Control            367230 non-null  object
 30  Crash_Speed_Limit                367227 non-null  object
 31  Crash_Road_Surface_Condition     367230 non-null  object
 32  Crash_Atmospheric_Condition      367230 non-null  object
 33  Crash_Lighting_Condition         367230 non-null  object
 34  Crash_Road_Horiz_Align           367230 non-null  object
 35  Crash_Road_Vert_Align            367229 non-null  object
 36  Crash_DCA_Code                   367146 non-null  float64
 37  Crash_DCA_Description            367146 non-null  object
 38  Crash_DCA_Group_Description      367230 non-null  object
 39  DCA_Key_Approach_Dir             361749 non-null  object
 40  Count_Casualty_Fatality          367230 non-null  int64
 41  Count_Casualty_Hospitalised      367230 non-null  int64
 42  Count_Casualty_MedicallyTreated  367230 non-null  int64
 43  Count_Casualty_MinorInjury       367230 non-null  int64
 44  Count_Casualty_Total             367230 non-null  int64
 45  Count_Unit_Car                   367230 non-null  int64
 46  Count_Unit_Motorcycle_Moped      367230 non-null  int64
 47  Count_Unit_Truck                 367230 non-null  int64
 48  Count_Unit_Bus                   367230 non-null  int64
 49  Count_Unit_Bicycle               367230 non-null  int64
 50  Count_Unit_Pedestrian            367230 non-null  int64
 51  Count_Unit_Other                 367230 non-null  int64
dtypes: float64(3), int64(15), object(34)
memory usage: 145.7+ MB

we would be keeping the following columns:

1.Crash_ref_Number, 2.Crash_Severity, 3.Crash_Year, 4.Crash_Month, 5.Crash_Day_Of_Week, 6.Crash_Nature,
7.Crash_Type, 8.Loc_ABS_Remoteness, 9.Crash_Roadway_Feature, 10.Crash_Traffic_Control , 11.Crash_Speed_Limit
12.Loc_Police_Region, 13.Crash_Atmospheric_Condition, 14.Crash_Lighting_Condition, 15.Crash_DCA_Code, 16.Crash_DCA_Group_Description
17.Count_Casualty_Fatality, 18.Count_Casualty_Hospitalised, 19.Count_Casualty_MedicallyTreated, 20.Count_Casualty_MinorInjury,
21.Count_Casualty_Total, 22.Count_Unit_Car, 23.Count_Unit_Motorcycle_Moped, 24.Count_Unit_Truck, 25.Count_Unit_Bus,
26.Count_Unit_Bicycle, 28.Count_Unit_Pedestrian, 29.Count_Unit_Other

In [49]:
loc_crash = crash_loc[['Crash_Ref_Number','Crash_Severity', 'Crash_Year', 'Crash_Month','Crash_Day_Of_Week','Crash_Nature',
                       'Crash_Type','Loc_ABS_Remoteness','Crash_Roadway_Feature','Crash_Traffic_Control', 
                       'Crash_Speed_Limit','Loc_Police_Region','Crash_Atmospheric_Condition','Crash_Lighting_Condition', 
                       'Crash_DCA_Code','Crash_DCA_Group_Description','Count_Casualty_Fatality','Count_Casualty_Hospitalised', 
                       'Count_Casualty_MedicallyTreated','Count_Casualty_MinorInjury','Count_Casualty_Total', 
                       'Count_Unit_Car', 'Count_Unit_Motorcycle_Moped', 'Count_Unit_Truck', 'Count_Unit_Bus', 
                       'Count_Unit_Bicycle', 'Count_Unit_Pedestrian','Count_Unit_Other']].copy()

loc_crash

,Crash_Ref_Number,Crash_Severity,Crash_Year,Crash_Month,Crash_Day_Of_Week,Crash_Nature,Crash_Type,Loc_ABS_Remoteness,Crash_Roadway_Feature,Crash_Traffic_Control,Crash_Speed_Limit,Loc_Police_Region,Crash_Atmospheric_Condition,Crash_Lighting_Condition,Crash_DCA_Code,Crash_DCA_Group_Description,Count_Casualty_Fatality,Count_Casualty_Hospitalised,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_Total,Count_Unit_Car,Count_Unit_Motorcycle_Moped,Count_Unit_Truck,Count_Unit_Bus,Count_Unit_Bicycle,Count_Unit_Pedestrian,Count_Unit_Other
0,1,Hospitalisation,2001,January,Monday,Head-on,Multi-Vehicle,Major Cities,No Roadway Feature,No traffic control,0 - 50 km/h,Brisbane,Clear,Daylight,201.0,Head-on,0,1,0,0,1,1,0,0,0,1,0,0
1,2,Property damage only,2001,January,Wednesday,Angle,Multi-Vehicle,Major Cities,No Roadway Feature,No traffic control,60 km/h,Brisbane,Clear,Daylight,406.0,Vehicle leaving driveway,0,0,0,0,0,2,0,0,0,0,0,0
2,3,Minor injury,2001,January,Thursday,Rear-end,Multi-Vehicle,Major Cities,Intersection - Cross,Operating traffic lights,60 km/h,Brisbane,Clear,Daylight,301.0,Rear-end,0,0,0,1,1,2,0,0,0,0,0,0
3,4,Property damage only,2001,January,Sunday,Hit object,Single Vehicle,Major Cities,Intersection - T-Junction,Operating traffic lights,60 km/h,Brisbane,Clear,Daylight,703.0,Off carriageway on straight hit object,0,0,0,0,0,1,0,0,0,0,0,0
4,5,Property damage only,2001,January,Tuesday,Overturned,Single Vehicle,Unknown,No Roadway Feature,No traffic control,60 km/h,Unknown,Clear,Daylight,702.0,Off carriageway on straight,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367225,367226,Medical treatment,2018,July,Friday,Rear-end,Multi-Vehicle,Major Cities,Intersection - Cross,Operating traffic lights,60 km/h,Brisbane,Clear,Daylight,301.0,Rear-end,0,0,1,0,1,1,1,0,0,0,0,0
367226,367227,Medical treatment,2018,July,Saturday,Angle,Multi-Vehicle,Major Cities,Intersection - T-Junction,Operating traffic lights,60 km/h,Brisbane,Clear,Daylight,105.0,Intersection from adjacent approaches,0,0,1,0,1,2,0,0,0,0,0,0
367227,367228,Hospitalisation,2018,July,Monday,Hit pedestrian,Hit pedestrian,Major Cities,Intersection - T-Junction,Operating traffic lights,60 km/h,Brisbane,Clear,Dawn/Dusk,1.0,Pedestrian,0,1,0,0,1,1,0,0,0,0,1,0
367228,367229,Medical treatment,2018,July,Tuesday,Angle,Multi-Vehicle,Major Cities,Intersection - T-Junction,No traffic control,80 - 90 km/h,Brisbane,Clear,Daylight,308.0,Parallel lanes turning,0,0,1,0,1,2,0,0,0,0,0,0
367229,367230,Medical treatment,2018,July,Monday,Hit object,Single Vehicle,Major Cities,No Roadway Feature,No traffic control,70 km/h,Brisbane,Clear,Darkness - Not lighted,804.0,Off carriageway on curve hit object,0,0,1,0,1,1,0,0,0,0,0,0

In [50]:
loc_crash.isnull().sum()
#let us drop the nul values since they are not much

Crash_Ref_Number                    0
Crash_Severity                      0
Crash_Year                          0
Crash_Month                         0
Crash_Day_Of_Week                   0
Crash_Nature                        0
Crash_Type                          0
Loc_ABS_Remoteness                  0
Crash_Roadway_Feature               0
Crash_Traffic_Control               0
Crash_Speed_Limit                   3
Loc_Police_Region                   0
Crash_Atmospheric_Condition         0
Crash_Lighting_Condition            0
Crash_DCA_Code                     84
Crash_DCA_Group_Description         0
Count_Casualty_Fatality             0
Count_Casualty_Hospitalised         0
Count_Casualty_MedicallyTreated     0
Count_Casualty_MinorInjury          0
Count_Casualty_Total                0
Count_Unit_Car                      0
Count_Unit_Motorcycle_Moped         0
Count_Unit_Truck                    0
Count_Unit_Bus                      0
Count_Unit_Bicycle                  0
Count_Unit_Pedestrian               0
Count_Unit_Other                    0
dtype: int64

In [51]:
loc_crash.dropna(subset=['Crash_Speed_Limit','Crash_DCA_Code'],inplace =True)

In [52]:
road_cas.isnull().sum()

Crash_Year               0
Crash_Police_Region      0
Casualty_Severity        0
Casualty_AgeGroup        0
Casualty_Gender          0
Casualty_RoadUserType    0
Casualty_Count           0
dtype: int64

In [53]:
restraint.isnull().sum()

Crash_Year                       0
Crash_PoliceRegion               0
Casualty_Severity                0
Casualty_AgeGroup                0
Casualty_Gender                  0
Casualty_Road_User_Type          0
Casualty_Restraint_Helmet_Use    0
Casualty_Count                   0
dtype: int64

In [54]:
factors.isnull().sum()

Crash_Year                     0
Crash_Police_Region            0
Crash_Severity                 0
Involving_Drink_Driving        0
Involving_Driver_Speed         0
Involving_Fatigued_Driver      0
Involving_Defective_Vehicle    0
Count_Crashes                  0
Count_Fatality                 0
Count_Hospitalised             0
Count_Medically_Treated        0
Count_Minor_Injury             0
Count_All_Casualties           0
dtype: int64

Apart from the loc_crash dataset, the datasets we would be using in our analysis does not have missing values

### 2.3 Dealing with duplicates

In [55]:
#checking for duplicates in loc_crash
duplicates_loc = loc_crash[loc_crash.duplicated()]
num_duplicates_loc = duplicates_loc.shape[0]
num_duplicates_loc

0

In [56]:
#checking for duplicates in road_cas
duplicates_cas = road_cas[road_cas.duplicated()]
num_duplicates_cas = duplicates_cas.shape[0]
num_duplicates_cas

5

In [57]:
#Since they are 5 duplicates in road casualties we drop them
road_cas.drop_duplicates(inplace = True)

In [58]:
#checking for duplicates in restraint
duplicates_res = restraint[restraint.duplicated()]
num_duplicates_res = duplicates_res.shape[0]
num_duplicates_res

4

In [59]:
restraint.drop_duplicates(inplace = True)

In [60]:
#checking for duplicates in factors
duplicates_fac = factors[factors.duplicated()]
num_duplicates_fac = duplicates_fac.shape[0]
num_duplicates_fac

0

In [61]:
loc_crash['Count_Unit_Motorcycle_Moped'].value_counts()

0    334170
1     32323
2       612
3        29
4         6
5         3
Name: Count_Unit_Motorcycle_Moped, dtype: int64

### Conclusion

We have been able to sucessfully clean Dataset by removing NaN values, dealing with inconsistent datatypes and finally dropping columns. We can now move forward to extracting our clean data for the analysis.

In [62]:
loc_crash.to_csv("crash_locations.csv",index=False)
loc_crash.head()

,Crash_Ref_Number,Crash_Severity,Crash_Year,Crash_Month,Crash_Day_Of_Week,Crash_Nature,Crash_Type,Loc_ABS_Remoteness,Crash_Roadway_Feature,Crash_Traffic_Control,Crash_Speed_Limit,Loc_Police_Region,Crash_Atmospheric_Condition,Crash_Lighting_Condition,Crash_DCA_Code,Crash_DCA_Group_Description,Count_Casualty_Fatality,Count_Casualty_Hospitalised,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_Total,Count_Unit_Car,Count_Unit_Motorcycle_Moped,Count_Unit_Truck,Count_Unit_Bus,Count_Unit_Bicycle,Count_Unit_Pedestrian,Count_Unit_Other
0,1,Hospitalisation,2001,January,Monday,Head-on,Multi-Vehicle,Major Cities,No Roadway Feature,No traffic control,0 - 50 km/h,Brisbane,Clear,Daylight,201.0,Head-on,0,1,0,0,1,1,0,0,0,1,0,0
1,2,Property damage only,2001,January,Wednesday,Angle,Multi-Vehicle,Major Cities,No Roadway Feature,No traffic control,60 km/h,Brisbane,Clear,Daylight,406.0,Vehicle leaving driveway,0,0,0,0,0,2,0,0,0,0,0,0
2,3,Minor injury,2001,January,Thursday,Rear-end,Multi-Vehicle,Major Cities,Intersection - Cross,Operating traffic lights,60 km/h,Brisbane,Clear,Daylight,301.0,Rear-end,0,0,0,1,1,2,0,0,0,0,0,0
3,4,Property damage only,2001,January,Sunday,Hit object,Single Vehicle,Major Cities,Intersection - T-Junction,Operating traffic lights,60 km/h,Brisbane,Clear,Daylight,703.0,Off carriageway on straight hit object,0,0,0,0,0,1,0,0,0,0,0,0
4,5,Property damage only,2001,January,Tuesday,Overturned,Single Vehicle,Unknown,No Roadway Feature,No traffic control,60 km/h,Unknown,Clear,Daylight,702.0,Off carriageway on straight,0,0,0,0,0,1,0,0,0,0,0,0

In [63]:
road_cas.to_csv("road_casualties.csv",index=False)
road_cas.head()

,Crash_Year,Crash_Police_Region,Casualty_Severity,Casualty_AgeGroup,Casualty_Gender,Casualty_RoadUserType,Casualty_Count
0,2006,North Coast,Medically treated,40 to 49,Female,Driver,71
1,2006,South Eastern,Medically treated,40 to 49,Male,Driver,54
2,2006,Southern,Medically treated,0 to 16,Female,Pedestrian,7
3,2007,North Coast,Medically treated,40 to 49,Male,Passenger,6
4,2007,Southern,Medically treated,17 to 24,Female,Driver,79

In [64]:
restraint.to_csv("restraint.csv",index=False)
restraint.head()

,Crash_Year,Crash_PoliceRegion,Casualty_Severity,Casualty_AgeGroup,Casualty_Gender,Casualty_Road_User_Type,Casualty_Restraint_Helmet_Use,Casualty_Count
0,2001,Brisbane,Fatality,0 to 16,Female,Vehicle Occupant,Restrained,1
1,2001,Brisbane,Fatality,17 to 24,Female,Vehicle Occupant,Restrained,1
2,2001,Brisbane,Fatality,25 to 29,Female,Vehicle Occupant,Restraint Use Not determined,1
3,2001,Brisbane,Fatality,30 to 39,Female,Vehicle Occupant,Restraint Use Not determined,1
4,2001,Brisbane,Fatality,30 to 39,Female,Vehicle Occupant,Unrestrained,1

In [65]:
factors.to_csv("factors.csv",index=False)
factors.head()
#end

,Crash_Year,Crash_Police_Region,Crash_Severity,Involving_Drink_Driving,Involving_Driver_Speed,Involving_Fatigued_Driver,Involving_Defective_Vehicle,Count_Crashes,Count_Fatality,Count_Hospitalised,Count_Medically_Treated,Count_Minor_Injury,Count_All_Casualties
0,2001,Brisbane,Fatal,No,No,No,No,25,25,6,4,2,37
1,2001,Brisbane,Fatal,No,No,No,Yes,1,1,0,0,0,1
2,2001,Brisbane,Fatal,No,Yes,No,No,8,8,5,0,0,13
3,2001,Brisbane,Fatal,Yes,No,No,No,2,2,0,0,0,2
4,2001,Brisbane,Fatal,Yes,No,No,Yes,1,1,3,0,0,4